import os
import json

from abc import ABC, abstractmethod

from dotenv import load_dotenv
load_dotenv()

import logging
logger = logging.getLogger(__name__)

from constants.comfyui import MK_LORA_TRIGGER_WORDS, SEED, TEXT, WORKFLOW_PATH
from clients.http import HTTPClient
from clients.smtp import smtp_client
from clients.s3 import s3
from database.models.image import Image
from database.models.prompt import Prompt
from templates.email_content import EmailContentTemplates

class ComfyUIBaseClient(ABC):
    def __init__(self):
        self._http = os.getenv('HTTP')
        self._server_address = os.getenv('COMFYUI_SERVER')
        self._url = f"{self._http}://{self._server_address}"
        self._prompt_url = f"{self._url}/prompt"
        self._history_url = f"{self._url}/history"
        self._image_url = f"{self._url}/view"
        self._workflow = self._load_workflow()
        
    def _load_workflow(self):
        logger.debug(f"Loading workflow from path: {WORKFLOW_PATH}")

        with open(WORKFLOW_PATH, "r", encoding="utf-8") as f:
            workflow = json.load(f)
        return workflow
    
    def _queue_prompt(self, client_id=None, prompt_id=None):
        logger.debug(f"Queueing prompt into ComfyUI with workflow.")
        
        # prompt for comfyui is worflow
        logger.debug("Attaching workflow to payload")
        payload = {"prompt": self._workflow}
        
        # an identifier ComfyUI uses to associate requests/events with that client
        if client_id:
            logger.debug(f"Attaching client_id: {client_id} to payload")
            payload["client_id"] = client_id
        
        # explicit pass prompt_id, else rely on prompt_id generated by comfyui and sent in response
        if prompt_id:
            logger.debug(f"Attaching explicit prompt_id: {prompt_id} to payload")
            payload["prompt_id"] = prompt_id

        logger.debug(f"Final payload: {payload}")

        data = json.dumps(payload).encode("utf-8")
        return json.loads(HTTPClient.fetch(self._prompt_url, data=data).decode())
 
    def _get_history(self, prompt_id):
        logger.debug(f"Fetching history for prompt_id: {prompt_id}")
        return json.loads(HTTPClient.fetch(f"{self._history_url}/{prompt_id}").decode())
    
    def _get_image(self, image_file):
        params = {
        "filename": image_file["filename"],
        "subfolder": image_file["subfolder"],
        "type": image_file["type"]
        }
        
        logger.debug(f"Fetching image with parameters: {params}")
        return HTTPClient.fetch(self._image_url, params=params)
    
    def _load_values_in_template(self, prompt_text, seed):
        logger.debug(f"Loading values into workflow template: prompt_text='{prompt_text}', seed={seed}")
        self._workflow[TEXT["NODE_INDEX"]]["inputs"][TEXT["VALUE"]] = MK_LORA_TRIGGER_WORDS + ", " + prompt_text 
        self._workflow[SEED["NODE_INDEX"]]["inputs"][SEED["VALUE"]] = seed
    
    def _get_outputs_from_history(self, history, prompt_id):
        logger.debug(f"Extracting outputs from history for prompt_id: {prompt_id}")

        outputs = history.get(prompt_id, {}).get("outputs")
        if outputs:
            logger.info(f"Outputs found for prompt_id: {prompt_id}")
            return outputs
        
        logger.warning(f"No outputs found for prompt_id: {prompt_id}")
        return None
    
    def _extract_image_from_outputs(self, outputs):
        logger.debug(f"Extracting image from outputs: {outputs}")

        for node_output in outputs.values():
            images = node_output.get("images")

            if not images:
                continue

            image = images[0]
            logger.debug(f"Image found in outputs: {image}")

            image_bytes = self._get_image(image)

            logger.debug(f"Image bytes fetched successfully, size: {len(image_bytes)} bytes")

            return {
                "filename": image["filename"], 
                "image_bytes": image_bytes,
                "maintype": "image",
                "subtype": "png"
                }

        logger.warning(f"Image not found in outputs.")
        return None
    
    def _retrieve_image(self, prompt_id):
        history = self._get_history(prompt_id)
        outputs = self._get_outputs_from_history(history, prompt_id)

        if not outputs:
            return None

        return self._extract_image_from_outputs(outputs)
    
    def _deliver_image(self, image, user, prompt, seed, collections):
        if image:  
            status = "success"
            filename = image["filename"] 
                
            logger.info(f"Sending email notification for prompt_id: {prompt['id']} to user {user['id']} ({user['email']}).")
            smtp_client.send_email(
                to_address=user["email"],
                subject=f"🎨🖼️ Your Marin Kitagawa Image Is Ready! 🌸💕",
                content={
                    "text": EmailContentTemplates.get_plain_text_email_content(prompt, seed),
                    "html": EmailContentTemplates.get_html_email_content(prompt, seed)
                },
                image_attachment=image
                )
                
            s3_key = f"{user['id']}/generated/{prompt['id']}.{image['subtype']}"
            logger.info(f"Uploading image to S3: s3_key={s3_key}, prompt_id={prompt['id']}, user_id={user['id']}.")
            s3.upload_image(image, s3_key)
        else:
            status = "failed"
            filename = None
            s3_key = None
                
        logger.info(f"Saving {status} image details to database for prompt_id: {prompt['id']}.")
        collections["images"].insert_one(Image(
            seed=seed,
            prompt_id=prompt["id"],
            status=status,
            filename=filename,
            s3_key=s3_key,
            created_by=user["id"]
        ).model_dump())        
        
    def queue_image(self, prompt_text, seed, client_id=None, prompt_id=None):
        logger.debug(f"Queueing image with prompt_text='{prompt_text}' and seed={seed}")
    
        self._load_values_in_template(prompt_text, seed)
            
        prompt_response = self._queue_prompt(client_id, prompt_id)
        prompt_id = prompt_response["prompt_id"]
    
        logger.debug(f"Prompt queued successfully with prompt_id: {prompt_id}")
        return prompt_id
    
    @abstractmethod
    async def _generate_image(self, prompt_id, client_id):
        ...
    
    async def generate_image(self, user, prompt, seed, collections, client_id=None):
        try:
            logger.debug(f"Saving prompt in database for prompt_id: {prompt['id']}.")
            collections["prompts"].insert_one(Prompt(
                id=prompt["id"],
                text=prompt["text"],
                created_by=user["id"]
            ).model_dump())
                
            image = await self._generate_image(prompt["id"], client_id)
            
            self._deliver_image(image, user, prompt, seed, collections)
        except Exception as e:
            logger.error(f'Failed to generate image: {str(e)}')